mock rest + sample draft implementation
ctco/cukes pull request #130
Opened 2018-05-10 11:21 UTC by mike-hmelov

2018-05-10 13:08 UTC, sergeytrasko requested changes
Why it's cukes-mock-rest? Is it applicable to pure http as well? Also I believe it can be applicable for graphql as well.

I would propose to rename modules to cukes-http-mock and cukes-http-mock-samples accordingly.

2018-05-11 07:20 UTC, mike-hmelov commented
module was renamed to proposed variant

2018-05-11 07:27 UTC, sergeytrasko commented on cukes-samples/cukes-http-mock-sample/pom.xml
> +            <artifactId>cukes-mock-rest</artifactId>
Is it correct?

2018-05-11 07:28 UTC, sergeytrasko commented on pom.xml
> +		<module>cukes-mock-rest</module>
Please adjust it as well

2018-05-11 07:28 UTC, sergeytrasko commented on cukes-samples/pom.xml
> +		<module>cukes-mock-rest-sample</module>
Please adjust it as well

2018-05-11 07:28 UTC, sergeytrasko commented on cukes-http-mock/pom.xml
> +    <name>Cukes RESTful mock extension</name>
Adjust name

2018-05-11 10:59 UTC, sergeytrasko commented
Rejecting in favour of PR #132

2018-05-11 10:59 UTC, closed without merging